#!/bin/bash
# Copyright 2015 The Statify Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. See the AUTHORS file for names of
# contributors.

# Detects the operating system we're compiling on and outputs a file 
# specified by the first argument, which in turn gets read while 
# processing Makefile.

OUTPUT=$1

# Ensure that the correct arguments were passed
if test -z "$OUTPUT"; then
  echo "usage: $0 <output-filename>" >&2
  exit 1
fi

# Delete existing output, if it exists
rm -f $OUTPUT
touch $OUTPUT

# Test for existence of the $CXX variable; if it hasn't been defined,
# default to use g++.
if test -z "$CXX"; then
  CXX=g++
fi

# Test to see if the caller specified a lint tool; if not, we'll 
# attempt to default to cpplint.py, but if that isn't present on
# the system, we'll use 'fakelint', a do-nothing stub that lives
# in the scripts/ subdirectory.
if test -z "$LINT_TOOL"; then
  CPPLINT_PY=`which cpplint.py`
  if test -z "$CPPLINT_PY"; then
    LINT_TOOL=./scripts/fakelint.sh
  else
    LINT_TOOL="cpplint.py"
  fi
fi

# Add dependent libraries
LIBRARIES="-lpthread -lrt -levent"

# Check for curl library
if [ -n "`which curl-config`" ]; then
  LIBRARIES="$LIBRARIES `curl-config --libs`"
else
  echo "Error: curl-config not found. Please install libcurl on your system." >&2
  exit 1
fi

# Source files for the Statify daemon
STATIFYD_SOURCES=""
STATIFYD_SOURCES+='./src/log.cc '
STATIFYD_SOURCES+='./src/program_options.cc '
STATIFYD_SOURCES+='./src/statifyd.cc '

# Source files for the Statify library
STATIFY_SOURCES=""
STATIFY_SOURCES+='./src/buffer.cc '
STATIFY_SOURCES+='./src/statify.cc '

# Lint sources
CPPLINT_SOURCES+='./src/*.cc '
CPPLINT_SOURCES+='./include/statify/*.h '

# Emit variables
echo "STATIFYD_SOURCES=$STATIFYD_SOURCES" >> $OUTPUT
echo "STATIFY_SOURCES=$STATIFY_SOURCES" >> $OUTPUT
echo "CPPLINT_SOURCES=$CPPLINT_SOURCES" >> $OUTPUT
echo "CXX=$CXX" >> $OUTPUT
echo "LIBRARIES=$LIBRARIES" >> $OUTPUT
echo "LINT_TOOL=$LINT_TOOL" >> $OUTPUT
